import { ConnectDatabase } from "@/utils/ConnectDatabase";
export const metadata = {
  title: "hello",
  description: "Generated by Next.js",
};

export default function ApiLayout({ children }) {
  return (
    <>
      {ConnectDatabase()}
      new layout
      {children}
    </>
  );
}
